seed: 42
device: "mps"  # cpu or cuda
overwrite: False
save: False

input:
  path: datasets
  batch_size: 50
  ### REMEMBER TO CHANGE BOTH THIS AND THE DATASET NAME IN DEFAULT ###
  dataset: "GTSRB" # "mnist" or "fmnist" or "cifar10" or "cifar100" or GTSRB or flowers or stl or oxfordpets
  classes_allowed: [0,1,2,3,4,5,6,7,8,9] # Number of classes to use from GTSRB dataset.
  number_samples: # Number of samples to use for training and testing for quicker runs.

defaults:
  - _self_
  - FFCCVAE: GTSRB.yaml  # Default dataset config. Override via: python main.py dataset=mnist input.dataset=mnist

model:

  peer_normalization: 0.03
  momentum: 0.9  # Momentum to use for the running mean in peer normalization loss.
  droprate: 0.1 # Dropout rate.

training:
  training_mode: "ff" # Either ff, bp or bp_ff
  elbo_kind: "MSE" # Either mse (mean squared error) or ce (cross entropy)

  epochs: 55 # 12 or 40 or 50

  optimizer: "Adam"  # "Adam" or "SGD"
  learning_rate: 1e-3
  weight_decay: 3e-4
  momentum: 0.9
  betas: [0.9, 0.999]

  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-3

  val_idx: -1  # -1: validate only once training has finished; n: validate every n epochs.
  final_test: True  # Set to true to evaluate performance on test-set.


hydra:
  run:
    dir: logs

